# Use a larger VM as we run a lot of services
# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: required
dist: trusty

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

language: java

# Spark doesn't support Java 9+, yet https://issues.apache.org/jira/browse/SPARK-24421
jdk:
  - oraclejdk8

services:
  - mysql
  - docker

cache:
  directories:
  - $HOME/.m2

before_install:
  # install mysql schema
  - mysql -uroot -e 'SET GLOBAL innodb_file_format=Barracuda'
  - mysql -uroot -e 'create database if not exists zipkin'
  - curl -SL https://raw.githubusercontent.com/apache/incubator-zipkin/master/zipkin-storage/mysql-v1/src/main/resources/mysql.sql | mysql -uroot -Dzipkin
  # Required for Elasticsearch 5 (See https://github.com/docker-library/docs/tree/master/elasticsearch#host-setup)
  - sudo sysctl -w vm.max_map_count=262144

  # Override default travis to use the maven wrapper
  # Use quiet as shade plugin creates too many logs for Travis: The log length has exceeded the limit of 4 MB
install: ./mvnw -q install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: ./mvnw clean verify -B

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/637e968b45032d16ee26
    on_success: change
    on_failure: always
