# Use a larger VM as we run a lot of services
# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: required
dist: trusty

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

language: java

# Spark doesn't support Java 9+, yet https://issues.apache.org/jira/browse/SPARK-24421
jdk:
  - oraclejdk8

services:
  - mysql
  - docker

cache:
  directories:
  - $HOME/.m2

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "zipkinci"
  - git config user.email "zipkinci+zipkin-dev@googlegroups.com"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials
  # install mysql schema
  - mysql -uroot -e 'SET GLOBAL innodb_file_format=Barracuda'
  - mysql -uroot -e 'create database if not exists zipkin'
  - curl -sSL https://raw.githubusercontent.com/openzipkin/zipkin/master/zipkin-storage/mysql-v1/src/main/resources/mysql.sql | mysql -uroot -Dzipkin
  # Required for Elasticsearch 5 (See https://github.com/docker-library/docs/tree/master/elasticsearch#host-setup)
  - sudo sysctl -w vm.max_map_count=262144

# Override default travis to use the maven wrapper; skip license on travis due to #1512
install: ./mvnw install -DskipTests=true -Dlicense.skip=true -Dmaven.javadoc.skip=true -B -V
script: ./travis/publish.sh

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

env:
  global:
    # Ex. travis encrypt BINTRAY_USER=your_github_account
    - secure: "MbJZxjzu6FaQEUlpEQUy8zQIOUPu1JBYtOfm3fdN732N73kbaWxLnfLD2qHRNi+IOIwV8pJSAIRvedfMGZy98yEQ5EJ0m34t5+BhcZ3TtJVTRBV45Ns5fgjy5FdPGXq5H8vixf20V8PkNT5gdcRvTmN9PZkgyQ+ylL1mmyAOcqNLMRhkl/u74HhyghdE16d5oTHb4Bq+r1Zabo51EcN2JWnZLrNkOghCwf01uoXjNMiVfNbutFG01nKpkyEi5+iflZOrcfZD0QV416cK2XdECvLq+OS+yZEzcx6479SJzPT2u6pQgVB/WjLBNHsioCCY2pyyMuH8yYtJuaTAjq4PTonwt9Cr6loeAdbxzZ8FjRu7eOsezQPoS2l4Wd8yKkxIbvTF+xqI8qxzqADkXquChVajapK8NELw93S9mgsBD24e6lscGFnnjc59r5C+hv9a8x/+dcaPsy6+EjuowScBhG0M9ubdKUWpIRZ2TDbscd+W0ZNWeCrqWM0X4vgHeIgo9FAhfnV+TLKVZbddGU/OmoAtijnyACFrgQ+QduhNyM2zS4bWBYom4mE3oEr69+wxg8CTAqglWuZjFe/naVjWFSlpkYz4MerIuFV5Onb4cbFD87ZX7ZW+A2wRKpGpn5/GKZhQC6MOQfhZonghg0GhLT+INVPpOWlFXt2owa1gXzA="
    # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
    - secure: "wUf2GhMkuL2w9YaVR0NLgJkj05Gdg21gJt5RhKivSQ8Eqs3+HUT10b61eFUoQEfy5NqVOHJmp8y6+QRYn/x56P7rlp2ugPotHOQh8b72rDLsQfamXOdMef3dDucIIxvAWD9zdinP5TK5CqaafwyCItQnTQgIX3ZVxFO58HPSvl6qTv2sDbU40pYINMF8mFa3ymimyAIzzg/+6ENOZT+ZH9wymynoWHU4ztBjSrpWNPfiSaNiY7Bx6zSAfrEcxf3+KtdZog6l5sHHKEhWYEbkEqbynasaqde3QMa/Io8IfLgsS9jf4JtXOsocvsThFpci6wvkgSewE1JMNmu/N8ZEfYFZiNRd8i2pQ6OdJnP1jIEKKPnm4k9DdKvWaftbLhkQGOpRRQnhqYPNYyfhLW91DIJO2Blq2PrlxEo5ENKNCniBoVIXfnGGjkVYyLOHFcMWiPEc4eEvSln3HV/fFEt0gpBA+HWkALXgvkMnNJ/CzbNiU7XyOg47MtZxzK+cGRD0Nolcqr0V42g/z27ix4waGucj4z9NyKfQ6EBo3p2ZAcrzqMZvUPFoeVhlvxQNWo4p3QLKCaGhCkdtGvNTPlSeZVKV93OkMoT5i9qu6L9ExvUMhraZSADb0fYflJe1b79sCe4zT/dclWQYYBxX5I0tnsDx+zVFZIrIj4HU1NC+Tro="
    # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
    - secure: "DqcWMw/ymAoLEPSJEhJxY+Maoh0zwVLkKtXEWDHFh8QdpjGlQLqoOycz+BtacaL/Sb3voRYJpPUr0oxEcQ9ii2QLuFtwnTbUTSCgq29eeybNZbWXgkDh+V86r0v/jn4sYNZwwhLFcRbOJAXKOE7GfUL2lVMZnVamqphTAvYh9z9VdsBqLTYmR7MCza1I4KxifT3iTFJzzsshHM4QQ33PgkLMOkMfjyAvrxxB+s/NOiADao4PfDfWSAgSBSgsJT2pcAfX7ayOUGJCXCMzCZM01A6VL68zQ08sq1qg2ncsBgR/Stjfplzdxds28WHLEawWxYFH0/FN2khbocd1ipfF33lk9jruUrZL2jbEIPPLGfTzbjKpL/AoyUlWn02xiVL/R7O+JhQAytwl8Jzc7rTjyfDnngn3Q3lsrXZUzJQYPsIMYn8M76SPbXjRWho6yNmOx7QFeAXBqXeQLmH/FfvnUFnAvl63XfvMkdS+EUAEKCW8tmFEXsSYRKYe0MjnpdodTwcajonOH6gUugw4TOtbLa0ZF6Ddhr6Sz/JB/aURDLQfUPxReFrafoRXLEA2zSQ6pvC/zwljeiPRoFkci7147ck4Fp80SbtlPJ21D+7awBh6qPp/v9Pj0GWwujWjp/0gULm5ouiWAGD19fsPjExG4/laZZ0i6Mg7IKijaEF/vGo="
    # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
    - secure: "I2c6SBOqEWqyWZHP7ZR/cOt/N06S/MxHOX5CzL9Fj61uNOZPgCEiLf1XyVDNC6s315VpPpFBxQJbSaKPxjjiH6Kob+aWxzlvAnUdUK2idYCoYnelUxrJD+eDhmeT0Wbcqu97XwoPWqQCiQ6Wrr+HDBwlUK+XkMEWAyrvYfs61gPWwe6ZNEoFnbr0hZWxh5eNUVCB7qHqS1zy/ZgI/TrjiLVFAIVMFX3yIQrIOJTMP1jiKN5faGuLVAYJ8RiY1P+G20XDQrSSnLBbW5byCQWDCXd9gi2HCpISrDaPOpxjOvTwmUWKtdJY1dMMsOYBl4FNT2K6jHKcVoZTxUFOxlqUWs4JrTO9TMV8RHbfsuFdjFbNeZVD8A76rWeIjzHzvYXjnvtizaZhG1kRIjOz2M6GSaMWFzHmwbS/2jN8mE4GmKmZXTAeaCPs+p9gY8SbxaOy10o/2mIYnuYTBQhwLofBiyyUGhlZbvSLgIkqHGm+Jc+RCA0vwYyR5Q/FZy7OW1di+cot9pBBe9V15K9qBXaGtWiZ1fRmBBtXrBEPNBLcosxOySISxwv8vApvqi6ppkWEmSD/PFDcy26h/zBEtAAEuEkt3HVl+YeWXUVqcF2NkMOyhhHjZ1hk7hx5KugA4UzPvly3wz+paPhuoWS3DFJ1UlCCPGStQM5jSIegTvsHvIE="
    # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
    - secure: "wE0OhHDQ/MOwzlLxUF9cC1mfx60VBak1yWnDPPpqZcUy+r8I5O1IC3vz1lwIu4Y/H20AZtVRgSNTPmvnZuDjoDIgxE0fJp/q9udSrYkZeQL5K3awAyLkYHbRgVAQrFddNiuhC8prPoXdtmvpE43maZ7Po5YKA4ZfSzb+FQfB4ukSNDVR86kSqBYq8+TmR2GBmtZe13hov6IB+oIKJWiJj4Lmbsy0E4NKTzNQvSL5orSwpXjBqYY93cy/Q9qv2LIFKInlC3dsVoVQjawm00AzRJtw+xGdj3/pXj2iPVQNLXzvzSXft82l5ye/amE2rCL6CATm1j253D98NKzbjBOkGAo5EVkzrRHi1gIOwmHs/mWXhOY4LQcXZqVNR232SCRoP1GKT1fNsz2WUJwX5cjowTQhV6xbNxepdLuQM/UT4LwJDYNCYh2y7Otr0Zwvr9J1e6iRIBFSl8EHhKgFN9z7SA8p0C5Bf/AiBHp0fNWnUWuvQstlfT6ESrdA4gSZcTWcAw9VCrMlKTTGAeWI1hgyDXeDJPcqCrgbiFWi8U6S8OiCf9RCqh1c4ko05pcnz+XGnY+Bfv3nOTitDvX3lXQhl58rnQfbNr938P6cgz9jyJ5LdOTLKvnpzf7d2s2MYnQ/50CaxDAX0OvNejjyNudwvx46D30ARHNJvvtKqT62MOQ="

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/637e968b45032d16ee26
    on_success: change
    on_failure: always
