# yamllint --format github .github/workflows/readme_test.yml
---
name: readme_test

# These test build commands mentioned in various README.md files.
#
# This doesn't literally scrape the README.md, so we don't test documentation-only commits.
on:
  # We run tests on only on pull requests targeted at the master branch.
  # * This skips master pushes as it is rare things not done in PRs break, and conserves resources
  pull_request:
    branches: master
    paths-ignore: '**/*.md'

jobs:
  readme_test:
    runs-on: ubuntu-20.04  # newest available distribution, aka focal
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Cache Docker
        uses: actions/cache@v2
        with:
          path: ~/.docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: ${{ runner.os }}-docker
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: README.md  # Tests the build which is re-used for docker
        run: ./mvnw -T1C -q --batch-mode -DskipTests -Denforcer.fail=false package
      - name: docker/README.md
        run: build-bin/docker/docker_build openzipkin/zipkin-dependencies:test
        env:
          RELEASE_FROM_MAVEN_BUILD: true
